// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3ChallengeRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3ChallengeResponse *components.V3ChallengeResponse
}

func (o *V3ChallengeRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3ChallengeRequestResponse) GetV3ChallengeResponse() *components.V3ChallengeResponse {
	if o == nil {
		return nil
	}
	return o.V3ChallengeResponse
}
