// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3StartRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3StartResponse *components.V3StartResponse
}

func (o *V3StartRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3StartRequestResponse) GetV3StartResponse() *components.V3StartResponse {
	if o == nil {
		return nil
	}
	return o.V3StartResponse
}
