// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3TokenRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3TokenResponse *components.V3TokenResponse
}

func (o *V3TokenRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3TokenRequestResponse) GetV3TokenResponse() *components.V3TokenResponse {
	if o == nil {
		return nil
	}
	return o.V3TokenResponse
}
