// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type Error struct {
	// Code is an internal error code that describes the problem category of the request.
	Code *int64 `json:"code,omitempty"`
	// Message is an error message describing the problem with the request.
	Message string `json:"message"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
