// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AddressResponse struct {
	// An integer value indicating the overall address score determined as a result of address matching. A value >=100 indicates verified = TRUE.
	AddressScore *int64 `json:"addressScore,omitempty"`
	// A boolean value indicating if the city name was matched during address matching.
	City *bool `json:"city,omitempty"`
	// A float value indicating the distance score as a result of address matching.
	Distance *float64 `json:"distance,omitempty"`
	// A boolean value indicating if the postal code was matched during address matching.
	PostalCode *bool `json:"postalCode,omitempty"`
	// A boolean value indicating if the region was matched during address matching.
	Region *bool `json:"region,omitempty"`
	// A boolean value indicating if the street name was matched during address matching.
	Street *bool `json:"street,omitempty"`
	// An integer value indicating the street number score as a result of address matching.
	StreetNumber *int64 `json:"streetNumber,omitempty"`
}

func (o *AddressResponse) GetAddressScore() *int64 {
	if o == nil {
		return nil
	}
	return o.AddressScore
}

func (o *AddressResponse) GetCity() *bool {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *AddressResponse) GetDistance() *float64 {
	if o == nil {
		return nil
	}
	return o.Distance
}

func (o *AddressResponse) GetPostalCode() *bool {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *AddressResponse) GetRegion() *bool {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *AddressResponse) GetStreet() *bool {
	if o == nil {
		return nil
	}
	return o.Street
}

func (o *AddressResponse) GetStreetNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.StreetNumber
}
