// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/payfone/prove-sdk-server-go/internal/utils"
)

type AddressEntry struct {
	// Address is the street address of the individual.
	Address *string `default:"39 South Trail" json:"address"`
	// City of the individual.
	City *string `default:"San Antonio" json:"city"`
	// Extended address is the apartment number or other extended address information.
	ExtendedAddress *string `json:"extendedAddress,omitempty"`
	// Postal code is the zip code of the individual.
	PostalCode *string `default:"78285" json:"postalCode"`
	// Region is the state or locality of the individual.
	Region *string `default:"TX" json:"region"`
}

func (a AddressEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddressEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AddressEntry) GetAddress() *string {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *AddressEntry) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *AddressEntry) GetExtendedAddress() *string {
	if o == nil {
		return nil
	}
	return o.ExtendedAddress
}

func (o *AddressEntry) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *AddressEntry) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}
