// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdverseMediaResponseInternal struct {
	Date    *string `json:"date,omitempty"`
	Snippet *string `json:"snippet,omitempty"`
	Title   *string `json:"title,omitempty"`
	URL     *string `json:"url,omitempty"`
}

func (o *AdverseMediaResponseInternal) GetDate() *string {
	if o == nil {
		return nil
	}
	return o.Date
}

func (o *AdverseMediaResponseInternal) GetSnippet() *string {
	if o == nil {
		return nil
	}
	return o.Snippet
}

func (o *AdverseMediaResponseInternal) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *AdverseMediaResponseInternal) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
