// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AdverseMediaResponse struct {
	Date    *string `json:"Date,omitempty"`
	Snippet *string `json:"Snippet,omitempty"`
	Title   *string `json:"Title,omitempty"`
	URL     *string `json:"Url,omitempty"`
}

func (o *AdverseMediaResponse) GetDate() *string {
	if o == nil {
		return nil
	}
	return o.Date
}

func (o *AdverseMediaResponse) GetSnippet() *string {
	if o == nil {
		return nil
	}
	return o.Snippet
}

func (o *AdverseMediaResponse) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *AdverseMediaResponse) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
