// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AmlTypeListResponse struct {
	AmlType  *string             `json:"AmlType,omitempty"`
	Fields   []FieldTypeResponse `json:"Fields,omitempty"`
	ListHits *int64              `json:"ListHits,omitempty"`
}

func (o *AmlTypeListResponse) GetAmlType() *string {
	if o == nil {
		return nil
	}
	return o.AmlType
}

func (o *AmlTypeListResponse) GetFields() []FieldTypeResponse {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *AmlTypeListResponse) GetListHits() *int64 {
	if o == nil {
		return nil
	}
	return o.ListHits
}
