// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DataSourceIdentifiersResponseInternal struct {
	Dob   *bool `json:"dob,omitempty"`
	Last4 *bool `json:"last4,omitempty"`
	Ssn   *bool `json:"ssn,omitempty"`
}

func (o *DataSourceIdentifiersResponseInternal) GetDob() *bool {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *DataSourceIdentifiersResponseInternal) GetLast4() *bool {
	if o == nil {
		return nil
	}
	return o.Last4
}

func (o *DataSourceIdentifiersResponseInternal) GetSsn() *bool {
	if o == nil {
		return nil
	}
	return o.Ssn
}
