// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DataSourceEmailAddressResponseInternal struct {
	EmailAddress *bool `json:"emailAddress,omitempty"`
}

func (o *DataSourceEmailAddressResponseInternal) GetEmailAddress() *bool {
	if o == nil {
		return nil
	}
	return o.EmailAddress
}
