// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type EmailAddressResponse struct {
	// A boolean value indicating if the email address was matched during processing.
	EmailAddress *bool `json:"emailAddress,omitempty"`
}

func (o *EmailAddressResponse) GetEmailAddress() *bool {
	if o == nil {
		return nil
	}
	return o.EmailAddress
}
