// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type FieldTypeResponse struct {
	Name   *string `json:"Name,omitempty"`
	Source *string `json:"Source,omitempty"`
	Value  *string `json:"Value,omitempty"`
}

func (o *FieldTypeResponse) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *FieldTypeResponse) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *FieldTypeResponse) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
