// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type IdentifiersResponse struct {
	// A boolean value indicating if the date of birth was matched during processing.
	Dob *bool `json:"dob,omitempty"`
	// The results of the driver's license match*.
	DriversLicenseNumber *bool `json:"driversLicenseNumber,omitempty"`
	// The results of the driver's license state match*.
	DriversLicenseState *bool `json:"driversLicenseState,omitempty"`
	// A boolean value indicating if the last 4 digits of the social security number were matched during processing.
	Last4 *bool `json:"last4,omitempty"`
	// The results of the full SSN match*.
	Ssn *bool `json:"ssn,omitempty"`
}

func (o *IdentifiersResponse) GetDob() *bool {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *IdentifiersResponse) GetDriversLicenseNumber() *bool {
	if o == nil {
		return nil
	}
	return o.DriversLicenseNumber
}

func (o *IdentifiersResponse) GetDriversLicenseState() *bool {
	if o == nil {
		return nil
	}
	return o.DriversLicenseState
}

func (o *IdentifiersResponse) GetLast4() *bool {
	if o == nil {
		return nil
	}
	return o.Last4
}

func (o *IdentifiersResponse) GetSsn() *bool {
	if o == nil {
		return nil
	}
	return o.Ssn
}
