// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type IDVData struct {
	DataSource1        *DataSource `json:"dataSource1,omitempty"`
	DataSource2        *DataSource `json:"dataSource2,omitempty"`
	MultiCIPConfidence *string     `json:"multiCIPConfidence,omitempty"`
	MultiVerified      *bool       `json:"multiVerified,omitempty"`
}

func (o *IDVData) GetDataSource1() *DataSource {
	if o == nil {
		return nil
	}
	return o.DataSource1
}

func (o *IDVData) GetDataSource2() *DataSource {
	if o == nil {
		return nil
	}
	return o.DataSource2
}

func (o *IDVData) GetMultiCIPConfidence() *string {
	if o == nil {
		return nil
	}
	return o.MultiCIPConfidence
}

func (o *IDVData) GetMultiVerified() *bool {
	if o == nil {
		return nil
	}
	return o.MultiVerified
}
