// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Individual struct {
	// Addresses that belong to the individual.
	Addresses []AddressEntry `json:"addresses,omitempty"`
	// DOB is the date of birth of the individual.
	Dob *string `json:"dob,omitempty"`
	// Email addresses that belong to the individual.
	EmailAddresses []string `json:"emailAddresses,omitempty"`
	// First name of the individual.
	FirstName *string `json:"firstName,omitempty"`
	// Las name of the individual.
	LastName *string `json:"lastName,omitempty"`
	// SSN is the social security number of the individual.
	Ssn *string `json:"ssn,omitempty"`
}

func (o *Individual) GetAddresses() []AddressEntry {
	if o == nil {
		return nil
	}
	return o.Addresses
}

func (o *Individual) GetDob() *string {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *Individual) GetEmailAddresses() []string {
	if o == nil {
		return nil
	}
	return o.EmailAddresses
}

func (o *Individual) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *Individual) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *Individual) GetSsn() *string {
	if o == nil {
		return nil
	}
	return o.Ssn
}
