// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KYCFieldTypeResponseInternal struct {
	Name   *string `json:"name,omitempty"`
	Source *string `json:"source,omitempty"`
	Value  *string `json:"value,omitempty"`
}

func (o *KYCFieldTypeResponseInternal) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *KYCFieldTypeResponseInternal) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *KYCFieldTypeResponseInternal) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
