// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KYCInternal struct {
	AmlTypeLists []AmlTypeListResponseInternal `json:"amlTypeLists,omitempty"`
	TotalHits    *int64                        `json:"totalHits,omitempty"`
}

func (o *KYCInternal) GetAmlTypeLists() []AmlTypeListResponseInternal {
	if o == nil {
		return nil
	}
	return o.AmlTypeLists
}

func (o *KYCInternal) GetTotalHits() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalHits
}
