// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KYCInternal struct {
	AdverseMediaList []AdverseMediaResponseInternal `json:"adverseMediaList,omitempty"`
	AliasList        []string                       `json:"aliasList,omitempty"`
	AmlTypeLists     []AmlTypeListResponseInternal  `json:"amlTypeLists,omitempty"`
	TotalHits        *int64                         `json:"totalHits,omitempty"`
}

func (o *KYCInternal) GetAdverseMediaList() []AdverseMediaResponseInternal {
	if o == nil {
		return nil
	}
	return o.AdverseMediaList
}

func (o *KYCInternal) GetAliasList() []string {
	if o == nil {
		return nil
	}
	return o.AliasList
}

func (o *KYCInternal) GetAmlTypeLists() []AmlTypeListResponseInternal {
	if o == nil {
		return nil
	}
	return o.AmlTypeLists
}

func (o *KYCInternal) GetTotalHits() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalHits
}
