// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type NameResponse struct {
	// The first name score as a result of name matching.
	FirstName *int64 `json:"firstName,omitempty"`
	// The last name score as a result of name matching.
	LastName *int64 `json:"lastName,omitempty"`
	// The overall name score as a result of name matching. A value >=70 indicates verified = TRUE.
	NameScore *int64 `json:"nameScore,omitempty"`
}

func (o *NameResponse) GetFirstName() *int64 {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *NameResponse) GetLastName() *int64 {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *NameResponse) GetNameScore() *int64 {
	if o == nil {
		return nil
	}
	return o.NameScore
}
