// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Security struct {
	Auth *string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *Security) GetAuth() *string {
	if o == nil {
		return nil
	}
	return o.Auth
}
