// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type V3ChallengeIndividualRequest struct {
	// Addresses that belong to the individual.
	Addresses []V3ChallengeAddressEntryRequest `json:"addresses,omitempty"`
	// DOB is the date of birth of the individual.
	Dob *string `json:"dob,omitempty"`
	// Email addresses that belong to the individual.
	EmailAddresses []string `json:"emailAddresses,omitempty"`
	// First name of the individual.
	FirstName *string `json:"firstName,omitempty"`
	// Last name of the individual.
	LastName *string `json:"lastName,omitempty"`
	// SSN is the social security number of the individual.
	Ssn *string `json:"ssn,omitempty"`
}

func (o *V3ChallengeIndividualRequest) GetAddresses() []V3ChallengeAddressEntryRequest {
	if o == nil {
		return nil
	}
	return o.Addresses
}

func (o *V3ChallengeIndividualRequest) GetDob() *string {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *V3ChallengeIndividualRequest) GetEmailAddresses() []string {
	if o == nil {
		return nil
	}
	return o.EmailAddresses
}

func (o *V3ChallengeIndividualRequest) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *V3ChallengeIndividualRequest) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *V3ChallengeIndividualRequest) GetSsn() *string {
	if o == nil {
		return nil
	}
	return o.Ssn
}
