// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ChallengeRequest struct {
	// Correlation ID is the unique ID that Prove generates for the flow. It is returned from the Start endpoint and cannot be reused outside of a single flow.
	CorrelationID string `json:"correlationId"`
	// DOB, an optional challenge, is the date of birth in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
	Dob *string `json:"dob,omitempty"`
	// SSN is either the full or last 4 numbers of the social security number. Acceptable characters are: numeric.
	Ssn *string `json:"ssn,omitempty"`
}

func (o *V3ChallengeRequest) GetCorrelationID() string {
	if o == nil {
		return ""
	}
	return o.CorrelationID
}

func (o *V3ChallengeRequest) GetDob() *string {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *V3ChallengeRequest) GetSsn() *string {
	if o == nil {
		return nil
	}
	return o.Ssn
}
