// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type V3CompleteRequest struct {
	// Correlation ID is the unique ID of the flow. To continue the flow, the field will also be used for each of the subsequent API calls in the same flow.
	CorrelationID string                      `json:"correlationId"`
	Individual    V3CompleteIndividualRequest `json:"individual"`
}

func (o *V3CompleteRequest) GetCorrelationID() string {
	if o == nil {
		return ""
	}
	return o.CorrelationID
}

func (o *V3CompleteRequest) GetIndividual() V3CompleteIndividualRequest {
	if o == nil {
		return V3CompleteIndividualRequest{}
	}
	return o.Individual
}
