// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3CompleteResponse struct {
	Idv *IDVDataInternal `json:"idv,omitempty"`
	Kyc *KYCInternal     `json:"kyc,omitempty"`
	// Next contains the next set of allowed calls in the same flow.
	Next map[string]string `json:"next"`
	// Success returns true if the individual was verified successfully.
	Success bool `json:"success"`
}

func (o *V3CompleteResponse) GetIdv() *IDVDataInternal {
	if o == nil {
		return nil
	}
	return o.Idv
}

func (o *V3CompleteResponse) GetKyc() *KYCInternal {
	if o == nil {
		return nil
	}
	return o.Kyc
}

func (o *V3CompleteResponse) GetNext() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Next
}

func (o *V3CompleteResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
