// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type V3StartRequest struct {
	// Device ID is the ID of the device. Acceptable characters are: alphanumeric with symbols '-._+=/'.
	DeviceID *string `json:"deviceId,omitempty"`
	// DOB, an optional challenge, is the date of birth in this format: YYYY-MM-DD. Acceptable characters are: numeric with symbol '-'.
	Dob *string `json:"dob,omitempty"`
	// Email is the email address of the customer. Acceptable characters are: alphanumeric with symbols '@.+'.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// Final target URL is the URL where the end user will be redirected at the end of Instant Link flow. Acceptable characters are: alphanumeric with symbols '-._+=/:?'.
	FinalTargetURL *string `json:"finalTargetUrl,omitempty"`
	// Flow ID defines which flow to use during the transaction.
	FlowID *string `json:"flowId,omitempty"`
	// Flow type is based on the method used - either 'desktop' if using desktop or 'mobile' for iOS/Android native apps and mobile web. Acceptable options are: 'desktop' or 'mobile'.
	FlowType string `json:"flowType"`
	// IP address is the IP address of the device of the customer. Acceptable characters are: numeric with symbols ':.'.
	IPAddress *string `json:"ipAddress,omitempty"`
	// Last4SSN, an optional challenge, is the last 4 numbers of the social security number. Acceptable characters are: numeric.
	Last4SSN *string `json:"last4SSN,omitempty"`
	// Phone number is the number of the mobile phone. Acceptable characters are: alphanumeric with symbols '+'.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

func (o *V3StartRequest) GetDeviceID() *string {
	if o == nil {
		return nil
	}
	return o.DeviceID
}

func (o *V3StartRequest) GetDob() *string {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *V3StartRequest) GetEmailAddress() *string {
	if o == nil {
		return nil
	}
	return o.EmailAddress
}

func (o *V3StartRequest) GetFinalTargetURL() *string {
	if o == nil {
		return nil
	}
	return o.FinalTargetURL
}

func (o *V3StartRequest) GetFlowID() *string {
	if o == nil {
		return nil
	}
	return o.FlowID
}

func (o *V3StartRequest) GetFlowType() string {
	if o == nil {
		return ""
	}
	return o.FlowType
}

func (o *V3StartRequest) GetIPAddress() *string {
	if o == nil {
		return nil
	}
	return o.IPAddress
}

func (o *V3StartRequest) GetLast4SSN() *string {
	if o == nil {
		return nil
	}
	return o.Last4SSN
}

func (o *V3StartRequest) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}
