// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type V3StartResponse struct {
	// AuthToken is a bearer token for use by the Prove Client SDK.
	AuthToken string `json:"authToken"`
	// Correlation ID is the unique ID of the flow. To continue the flow, the field will also be used for each of the subsequent API calls in the same flow.
	CorrelationID string `json:"correlationId"`
	// Next contains the next set of allowed calls in the same flow.
	Next map[string]string `json:"next"`
}

func (o *V3StartResponse) GetAuthToken() string {
	if o == nil {
		return ""
	}
	return o.AuthToken
}

func (o *V3StartResponse) GetCorrelationID() string {
	if o == nil {
		return ""
	}
	return o.CorrelationID
}

func (o *V3StartResponse) GetNext() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Next
}
