// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/payfone/prove-sdk-server-go/internal/utils"
)

type V3StartRequest struct {
	// Device ID is the ID of the device. Acceptable characters are: alphanumeric with symbols '-._+=/'.
	DeviceID *string `default:"713189b8-5555-4b08-83ba-75d08780aebd" json:"deviceId"`
	// DOB, an optional challenge, is the date of birth in this format: YYYYY-MM-DD. Acceptable characters are: numeric with symbol '-'.
	Dob *string `default:"2024-05-02 00:00:00 +0000 UTC" json:"dob"`
	// Email is the email address of the customer. Acceptable characters are: alphanumeric with symbols '@.+'.
	EmailAddress *string `default:"jdoe@example.com" json:"emailAddress"`
	// Final target URL is the URL where the end user will be redirected at the end of Instant Link. Acceptable characters are: alphanumeric with symbols '-._+=/:?'.
	FinalTargetURL *string `default:"https://www.example.com/landing-page" json:"finalTargetUrl"`
	// Flow type is based on the method used  - either desktop for native for iOS/Android native apps or mobile web. Acceptable options are: native or web.
	FlowType *string `default:"mobile" json:"flowType"`
	// IP address is the IP address of the device of the customer. Acceptable characters are: numeric with symbols ':.'.
	IPAddress *string `default:"10.0.0.1" json:"ipAddress"`
	// Last4SSN, an optional challenge, is the last 4 numbers of the social security number. Acceptable characters are: numeric.
	Last4SSN *string `default:"1234" json:"last4SSN"`
	// Phone number is the number of the mobile phone. Acceptable characters are: alphanumeric with symbols '+'.
	PhoneNumber *string `default:"12065550100" json:"phoneNumber"`
}

func (v V3StartRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3StartRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3StartRequest) GetDeviceID() *string {
	if o == nil {
		return nil
	}
	return o.DeviceID
}

func (o *V3StartRequest) GetDob() *string {
	if o == nil {
		return nil
	}
	return o.Dob
}

func (o *V3StartRequest) GetEmailAddress() *string {
	if o == nil {
		return nil
	}
	return o.EmailAddress
}

func (o *V3StartRequest) GetFinalTargetURL() *string {
	if o == nil {
		return nil
	}
	return o.FinalTargetURL
}

func (o *V3StartRequest) GetFlowType() *string {
	if o == nil {
		return nil
	}
	return o.FlowType
}

func (o *V3StartRequest) GetIPAddress() *string {
	if o == nil {
		return nil
	}
	return o.IPAddress
}

func (o *V3StartRequest) GetLast4SSN() *string {
	if o == nil {
		return nil
	}
	return o.Last4SSN
}

func (o *V3StartRequest) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}
