// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3TokenResponse struct {
	// AccessToken returns the access token as a string.
	AccessToken string `json:"access_token"`
	// ExpiresIn returns the lifetime of the token in seconds.
	ExpiresIn int64 `json:"expires_in"`
	// RefreshExpiresIn returns the lifetime of the token in seconds. Not currently supported.
	RefreshExpiresIn *int64 `json:"refresh_expires_in,omitempty"`
	// RefreshToken returns the refresh token as a string. Not currently supported.
	RefreshToken *string `json:"refresh_token,omitempty"`
	// TokenType returns the type of token.
	TokenType string `json:"token_type"`
}

func (o *V3TokenResponse) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *V3TokenResponse) GetExpiresIn() int64 {
	if o == nil {
		return 0
	}
	return o.ExpiresIn
}

func (o *V3TokenResponse) GetRefreshExpiresIn() *int64 {
	if o == nil {
		return nil
	}
	return o.RefreshExpiresIn
}

func (o *V3TokenResponse) GetRefreshToken() *string {
	if o == nil {
		return nil
	}
	return o.RefreshToken
}

func (o *V3TokenResponse) GetTokenType() string {
	if o == nil {
		return ""
	}
	return o.TokenType
}
