// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type V3TokenRequest struct {
	// ClientID is the optional client ID.
	ClientID *string `json:"client_id,omitempty"`
	// GrantType only allows option: `password`.
	GrantType string `json:"grant_type"`
	// Password is the secret ID provided to the customer during onboarding.
	Password string `json:"password"`
	// Username is the ID provided to the customer during onboarding.
	Username string `json:"username"`
}

func (o *V3TokenRequest) GetClientID() *string {
	if o == nil {
		return nil
	}
	return o.ClientID
}

func (o *V3TokenRequest) GetGrantType() string {
	if o == nil {
		return ""
	}
	return o.GrantType
}

func (o *V3TokenRequest) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *V3TokenRequest) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
