// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type V3ValidateResponse struct {
	// Challenge missing returns true if a DOB or SSN needs to be passed in on the next step.
	ChallengeMissing bool `json:"challengeMissing"`
	// Next contains the next set of allowed calls in the same flow.
	Next map[string]string `json:"next"`
	// Success returns true if the phone number was validated.
	Success bool `json:"success"`
}

func (o *V3ValidateResponse) GetChallengeMissing() bool {
	if o == nil {
		return false
	}
	return o.ChallengeMissing
}

func (o *V3ValidateResponse) GetNext() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Next
}

func (o *V3ValidateResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
