// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type V3ValidateRequest struct {
	// Correlation ID is the unique ID that Prove generates for the flow. It is returned from the Start endpoint and cannot be reused outside of a single flow.
	CorrelationID string `json:"correlationId"`
}

func (o *V3ValidateRequest) GetCorrelationID() string {
	if o == nil {
		return ""
	}
	return o.CorrelationID
}
